//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publish
    {
        public long PublishId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string MediaUrl { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> FrequencyInDays { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
